### ISSUE TITLE
Wrap guide

### ISSUE THREAD

**Issue by jacobmischka** [defunkt/Zen#80]
I know this was addressed in #49, but it [seems to be back](http://i.imgur.com/dDicM9D.png)?

**Comment by jacobmischka** [comment]
In addition, esc also seems to not be closing zen for me either.

**Comment by braver** [comment]
Yes, esc should *not* exit Zen. Wrap guides should be hidden though...

**Comment by jacobmischka** [comment]
Oh, okay. I just saw that line in #49 and noticed it wasn't working. I should have looked to see if that was intentionally changed, my mistake. I see that the css that's supposed to hide the wrap guide is present in the stylesheets, but I don't know why it doesn't seem to be working.

**Comment by ntessore** [comment]
@jacobmischka I was able to hide the wrap guide with

```less
[data-zen="true"] {
    atom-text-editor::shadow .wrap-guide {
        visibility: hidden;
    }
}
```

in my personal stylesheet.
